# https://stuff.revi.xyz/u/dependabot
# for documentation link

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '13:00'
      timezone: 'Asia/Seoul'

  # Maintain dependencies for `npm` @ rootdir
  - package-ecosystem: 'npm'
    assignees:
      - 'revi'
    # npm package dependencies in the location of `package.json`.
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '13:00'
      timezone: 'Asia/Seoul'
    target-branch: 'master'
