name: Metrics
on:
  # Update every 3 hours
  schedule:
    - cron: "0 */3 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:

concurrency:
  group: readme

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: "Activity"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_limit: 5
          plugin_activity_days: 0
      - name: "Wakatime"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          user: revi
          plugin_wakatime_repositories_visibility: public
      - name: "Intro"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/intro.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_introduction: yes
          user: revi
      - name: "Steam"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198085745329"
          plugin_steam_games_limit: 3
          plugin_steam_recent_games_limit: 3
      - name: "Recent activity charts"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/habitchart.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Seoul
      - name: "Sponsors"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
      - name: "Followup"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/followupuser.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
      - name: "Last.fm  - Recently listened"
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/lastfm.svg
          base: ""
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: revinim
      - name: "Calendar"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: $ {{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: -2
