name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 */12 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: "Activity"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_limit: 5
          plugin_activity_days: 0
      - name: "Wakatime"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          user: revi
          plugin_wakatime_repositories_visibility: public
      - name: "Intro"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.intro.svg
          token: NOT_NEEDED
          base: header
          plugin_introduction: yes
          user: revi
      - name: "Steam"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198085745329"
          plugin_steam_games_limit: 3
                    plugin_steam_recent_games_limit: 3
      - name: "Recent activity charts"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.habitchart.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Seoul
      - name: "Sponsors"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
      - name: "Followup"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.followupuser.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
