name: Todoist Readme Update

on:
  workflow_dispatch:
#  schedule:
    # Runs at 14:45 UTC (23:45 KST) every day
#    - cron: '45 14 * * *'

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviforks/todoist-readme@committer
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true
