---
name: YAML Lint
on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - .yamllint
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - .yamllint
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install locale
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-ko
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
